### PR TITLE
Update to 1.17

### LINKED ISSUE #4: Add 1.17 Support
1.17 is out!

### PR DESCRIPTION
**Pull request by Eiim**
- Updates some dependencies, including Gradle
- Update for new Gradle version
- Various updates to 1.17 and Java 16
- Update for new 1.17 rendering system

Closes #4.

### CODE REVIEW

**Comment by ChainSwordCS** [comment]
Thanks @Eiim :)

**Comment by EsserGaming** [comment]
<3

**Comment by EsserGaming** [comment]
When the inactive developer...

**Comment by vladmarica** [comment]
Sorry for the delay and thanks for the PR. I will review, merge, and release the 1.17 update this week.

**Pull request merged**
