### PR TITLE
Add 1.20.4 support

### PR DESCRIPTION
**Pull request by joshuayuen99**

### CODE REVIEW

**Comment by vico93** [comment]
Does you have a compiled .jar of this fork?

**Comment by CheaterTim** [comment]
In the meanwhile you can modify the `fabric.mod.json` in the jar to specify `"minecraft": ">=1.20.2"`

**Comment by joshuayuen99** [comment]
> Does you have a compiled .jar of this fork?

I have uploaded it as a release here, though generally speaking I would recommend building yourself and not having to rely on trusting a .jar's authenticity. Hopefully @vladmarica will be able to release this officially soon.

https://github.com/joshuayuen99/better-ping-display-fabric/releases/tag/v1.20.4

**Comment by vladmarica** [comment]
Thanks for the pull request and sorry for the late response. I'm not going to accept PRs for simple version updates. I'll be updating the CONTRIBUTING guidelines.

**Pull request closed without merging**
